// <auto-generated />
namespace DanceApp1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class groupshowcase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(groupshowcase));
        
        string IMigrationMetadata.Id
        {
            get { return "202401241849081_group-showcase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
